Add frontend success msg notice
Meituan-Dianping/lyrebird pull request #502
Opened 2021-05-24 09:44 UTC by happylemon233

- Add frontend success msg notice

2021-06-28 05:36 UTC, zhaoye commented on frontend/src/views/Main.vue
> +      switch1: false,
变量名不规范 尽量表意，不要使用1、2、3之类的命名

2021-06-28 06:11 UTC, zhaoye requested changes

2021-06-28 06:11 UTC, zhaoye commented on frontend/src/views/notice/Alert.vue
> +        var index = 0
const or let

2021-06-28 06:11 UTC, zhaoye commented on frontend/public/index.html
> +    <!-- <meta name="viewport" content="width=device-width,initial-scale=1.0"> -->
是不是无用的注释。

2021-06-28 06:11 UTC, zhaoye commented on frontend/src/plugins/vuetify.js
> +// src/plugins/vuetify.js
无用的注释

2021-06-28 06:11 UTC, zhaoye commented on frontend/src/plugins/vuetify.js
> +//import Vuetify from'vuetify/lib'
无用的注释

2021-06-28 06:11 UTC, zhaoye commented on lyrebird/mock/blueprints/apis/menu.py
> +        plugin_icon = {
需要修改实现方式，可配置化处理

2021-06-28 06:11 UTC, zhaoye commented on lyrebird/project_builder/lyrebird_plugin_demo/frontend/public/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
plugin demo为什么需要这个

2021-07-02 10:33 UTC, yumiguan approved these changes

2021-07-05 12:39 UTC, merged